"""name

Revision ID: e2687034d6eb
Revises: 7bc2494cc2cc
Create Date: 2025-06-17 18:10:06.712300

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e2687034d6eb'
down_revision = '7bc2494cc2cc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=150), nullable=False))
        batch_op.alter_column('first_name',
               existing_type=sa.VARCHAR(length=75),
               nullable=True)
        batch_op.alter_column('last_name',
               existing_type=sa.VARCHAR(length=75),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('last_name',
               existing_type=sa.VARCHAR(length=75),
               nullable=False)
        batch_op.alter_column('first_name',
               existing_type=sa.VARCHAR(length=75),
               nullable=False)
        batch_op.drop_column('name')

    # ### end Alembic commands ###
