"""Add request_date to late_plates table

Revision ID: 1bf8c5b59f12
Revises: 65a02cdb7804
Create Date: 2026-01-04 22:36:11.463317

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1bf8c5b59f12'
down_revision = '65a02cdb7804'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('late_plates', schema=None) as batch_op:
        batch_op.add_column(sa.Column('request_date', sa.Date(), nullable=True))

    op.execute("UPDATE late_plates SET request_date = CURRENT_DATE WHERE request_date IS NULL")

    with op.batch_alter_table('late_plates', schema=None) as batch_op:
        batch_op.alter_column('request_date', nullable=False)
        batch_op.drop_constraint('user_meal_late_plate_uc', type_='unique')
        batch_op.create_unique_constraint('user_meal_late_plate_date_uc', ['user_id', 'meal_id', 'request_date'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('late_plates', schema=None) as batch_op:
        batch_op.drop_constraint('user_meal_late_plate_date_uc', type_='unique')
        batch_op.create_unique_constraint(batch_op.f('user_meal_late_plate_uc'), ['user_id', 'meal_id'], postgresql_nulls_not_distinct=False)
        batch_op.drop_column('request_date')

    # ### end Alembic commands ###
