"""Add is_admin to User model

Revision ID: 26045ae2f6f0
Revises: bfac39f3a773
Create Date: 2026-01-04 00:54:44.677017

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '26045ae2f6f0'
down_revision = 'bfac39f3a773'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_admin', sa.Boolean(), nullable=False, server_default='false'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('is_admin')

    # ### end Alembic commands ###
