"""add pickup_time late_plate_hours_before hidden confirmed house_settings

Revision ID: 8ee5c4311ba0
Revises: f6d3a3545d17
Create Date: 2026-02-18 14:32:42.200701

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8ee5c4311ba0'
down_revision = 'f6d3a3545d17'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('house_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=50), nullable=False),
    sa.Column('value', sa.String(length=200), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    with op.batch_alter_table('late_plates', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pickup_time', sa.Time(), nullable=True))

    with op.batch_alter_table('meal_attendance', schema=None) as batch_op:
        batch_op.add_column(sa.Column('confirmed', sa.Boolean(), nullable=True))

    with op.batch_alter_table('meals', schema=None) as batch_op:
        batch_op.add_column(sa.Column('late_plate_hours_before', sa.Integer(), nullable=True))

    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.add_column(sa.Column('hidden', sa.Boolean(), nullable=False, server_default='false'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.drop_column('hidden')

    with op.batch_alter_table('meals', schema=None) as batch_op:
        batch_op.drop_column('late_plate_hours_before')

    with op.batch_alter_table('meal_attendance', schema=None) as batch_op:
        batch_op.drop_column('confirmed')

    with op.batch_alter_table('late_plates', schema=None) as batch_op:
        batch_op.drop_column('pickup_time')

    op.drop_table('house_settings')
    # ### end Alembic commands ###
