"""add chapters table and chapter_id to users and meals

Revision ID: b18ef7b24fd0
Revises: 8ee5c4311ba0
Create Date: 2026-02-18 18:50:43.161968

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b18ef7b24fd0'
down_revision = '8ee5c4311ba0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chapters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('access_code', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('access_code'),
    sa.UniqueConstraint('name')
    )
    with op.batch_alter_table('meals', schema=None) as batch_op:
        batch_op.add_column(sa.Column('chapter_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'chapters', ['chapter_id'], ['id'])

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('chapter_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'chapters', ['chapter_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('chapter_id')

    with op.batch_alter_table('meals', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('chapter_id')

    op.drop_table('chapters')
    # ### end Alembic commands ###
