"""changing names

Revision ID: bfac39f3a773
Revises: e2687034d6eb
Create Date: 2025-06-17 18:22:01.736360

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bfac39f3a773'
down_revision = 'e2687034d6eb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('first_name',
               existing_type=sa.VARCHAR(length=75),
               nullable=False)
        batch_op.alter_column('last_name',
               existing_type=sa.VARCHAR(length=75),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('last_name',
               existing_type=sa.VARCHAR(length=75),
               nullable=True)
        batch_op.alter_column('first_name',
               existing_type=sa.VARCHAR(length=75),
               nullable=True)

    # ### end Alembic commands ###
